# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9c1b2ee5d39a30b6db9a77f8928ffe5c"
name = "Perceive A11y Auditor"
application_url = "https://perceive-a11y-auditor.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update", "app/uninstalled" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes"

[auth]
redirect_urls = [ "https://perceive-a11y-auditor.fly.dev/auth/callback", "https://perceive-a11y-auditor.fly.dev/api/auth" ]
