import type { LoaderFunctionArgs } from "@remix-run/node";
import { json } from "@remix-run/node";
import prisma from "~/lib/db.server";

/**
 * Public report page — accessible without Shopify login.
 *
 * Uses a one-time token to authenticate. This page is served outside the
 * Shopify admin iframe, so it uses Pico CSS + vanilla JS per CLAUDE.md.
 */
export const loader = async ({ params }: LoaderFunctionArgs) => {
  const token = params.token;
  if (!token) {
    throw new Response("Report not found", { status: 404 });
  }

  // TODO: Implement token-based report lookup.
  // For MVP, the token is the scan ID (will be replaced with
  // cryptographic one-time tokens before launch).
  const scanId = parseInt(token, 10);
  if (isNaN(scanId)) {
    throw new Response("Invalid report token", { status: 400 });
  }

  const scan = await prisma.scan.findUnique({
    where: { id: scanId },
    include: {
      findings: true,
      merchant: { select: { shopDomain: true } },
    },
  });

  if (!scan) {
    throw new Response("Report not found", { status: 404 });
  }

  return json({
    shopDomain: scan.merchant.shopDomain,
    completedAt: scan.completedAt?.toISOString() ?? null,
    filesScanned: scan.templateCount,
    findings: scan.findings.map((f) => ({
      criterionId: f.criterionId,
      severity: f.severity,
      element: f.element,
      filePath: f.filePath,
      line: f.line,
      message: f.message,
      suggestion: f.suggestion,
    })),
  });
};

/**
 * Public report page rendered with Pico CSS (no Polaris/React framework).
 * This is outside the Shopify admin iframe.
 */
export default function PublicReport() {
  // NOTE: This is a server-rendered page. In production, this would
  // be a plain HTML response with Pico CSS. For now, we return a
  // minimal React component that renders a static report page.
  // The actual implementation will use a separate HTML template.
  return (
    <html lang="en" data-theme="light">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Accessibility Report - Perceive A11y</title>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=JetBrains+Mono:wght@400&display=swap"
          rel="stylesheet"
        />
        <style
          dangerouslySetInnerHTML={{
            __html: `
              :root {
                --font-family: 'Inter', sans-serif;
                --pico-font-size: 16px;
              }
              code, pre { font-family: 'JetBrains Mono', monospace; }
              .severity-critical { color: #d72c0d; font-weight: 700; }
              .severity-serious { color: #b98900; font-weight: 600; }
              .severity-moderate { color: #5c6ac4; }
              .severity-minor { color: #637381; }
              .finding-card {
                border-left: 4px solid var(--pico-muted-border-color);
                padding: 1rem;
                margin-bottom: 1rem;
                background: var(--pico-card-background-color);
                border-radius: 0.25rem;
              }
              .finding-card.critical { border-left-color: #d72c0d; }
              .finding-card.serious { border-left-color: #b98900; }
              .finding-card.moderate { border-left-color: #5c6ac4; }
              header { text-align: center; margin-bottom: 2rem; }
              footer { text-align: center; margin-top: 3rem; padding: 2rem 0; }
            `,
          }}
        />
      </head>
      <body>
        <main className="container">
          <header>
            <h1>Accessibility Audit Report</h1>
            <p>
              Generated by{" "}
              <strong>Perceive A11y Auditor</strong> -- WCAG 2.2 static
              analysis
            </p>
          </header>

          <section id="report-content">
            <noscript>
              <p>This report requires JavaScript to display findings.</p>
            </noscript>
          </section>

          <footer>
            <small>
              This report was generated by source-code analysis of Shopify theme
              files. It covers static checks only and does not replace a full
              manual accessibility audit.
            </small>
          </footer>
        </main>

        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Fetch report data from the loader and render findings
              // This runs client-side to hydrate the static report
              document.addEventListener('DOMContentLoaded', function() {
                var container = document.getElementById('report-content');
                if (!container) return;
                // The data is embedded by Remix SSR - in production this will
                // be a plain HTML template with embedded JSON data
                container.innerHTML = '<p>Report loaded. Findings will appear here once connected to a live scan.</p>';
              });
            `,
          }}
        />
      </body>
    </html>
  );
}
